version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: dse
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
    - '3306:33600'
  node:
    container_name: test-node-mysql
    build: .
    restart: always
    ports:
      - '3000:3000'
    links:
    - db:mysql